apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Eshahmeer/E2E-Project-2.git'
    path: 'k8s/my-vikunja-app'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demoproject
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
