apiVersion: v1
kind: PersistentVolume
metadata:
  name: vikunja-pv
  namespace: demoproject
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/emumba/E2E-Project-2/db