apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  annotations:
  labels:
    product: aes
  name: vikunja-portal
  namespace: ambassador
spec:
  prefix: /
  rewrite: /
  service: vikunja.demoproject
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: vikunja-api
  namespace: ambassador
  labels:
    product: aes
spec:
  prefix: /api/
  rewrite: /api/
  service: vikunja.demoproject
